server:
  port: 8080
spring:
  application:
    name: ideas
  liquibase:
    enabled: true
    liquibase-schema: service_schema
    change-log: db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url:
    driver-class-name: org.postgresql.Driver
    username:
    password:
    type: org.postgresql.ds.PGSimpleDataSource
  kafka:
    bootstrap-servers:
    consumer:
      group-id:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger
    operations-sorter: method

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info
      base-path: /actuator

info:
  application:
    name: 'Ideas'
    description: 'Модуль Ideas для проекта ideas-service-4 '

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    history-level: full